### ISSUE TITLE
Not installing..?

### ISSUE THREAD

**Issue by FreeSpirit63** [envato/envato-wordpress-toolkit-library#13]
Hi Team,

When i try to install the Plugin as a Plugin it don't work.. It says this is not recognized as a plugin...
I used the master file but it won't work manual don't work either?

Any help?

Robert

**Comment by IgorCode** [comment]
This is not a plugin, it's a library for use in themes.

**Comment by valendesigns** [comment]
This library is also deprecated and will no longer function when the old API is turned off sometime early/mid 2016. The new plugin I've been working on is the replacement for both the plugin and library and works with themes & plugins and uses the new API.

**Comment by FreeSpirit63** [comment]
yes i noticed sorry my mistake...
