### ISSUE TITLE
Is it still supported?

### ISSUE THREAD

**Issue by pixedelic** [envato/envato-wordpress-toolkit-library#5]
Hi, thank you for this library, but I have some (maybe stupid) questions:
1. is it the library still supported?
2. since it doesn't seem to work on my end, could it depend on the fact it isn't supported anymore? Or maybe I need the API key and the username of a person who purchased the theme? I'm the developer and I'm not sure if the functions check if the username and the API key correspond to a user that purchase the theme.

TIA, Manuel :-)

**Comment by Japh** [comment]
Hi Manuel,
1. It is still supported!
2. You do need to have purchased the theme and use your username and API code. Unfortunately, there's not a testing API presently.

**Comment by Firestorm-Graphics** [comment]
on the subject of a testing api, isnt it time there was a api sandbox, kinda makes sense, i mean how is a first time seller supposed to test something that hasnt yet sold ?
